import {
  LayoutDashboard,
  Users,
  UserCheck,
  Image,
  Settings,
  FileText,
  PlayCircle,
  Bell,
  Newspaper,
  Smile,
  UserPlus,
  Layers,
  Users2,
  Wallet,
  Gift,
  Star,
  Blocks,
  ClipboardList,
  BookOpen,
  Coins,
  CreditCard,
  DollarSign,
  CalendarClock,
} from "lucide-react";

export const mainItems = [
  {
    title: "Dashboard",
    url: "/dashboard",
    icon: LayoutDashboard,
  },
  {
    title: "Customers",
    url: "/customers",
    icon: Users,
  },
  {
    title: "Astrologers",
    url: "#",
    icon: UserCheck,
    children: [
      { title: "Block Astrologer", url: "/astrologers/block-astrologer", icon: Blocks },
      { title: "Manage Astrologers", url: "/astrologers/manage-astrologers", icon: ClipboardList },
      { title: "Pending Requests", url: "/astrologers/pending-requests", icon: CalendarClock },
      { title: "Reviews", url: "/astrologers/reviews", icon: Star },
      { title: "Gifts", url: "/astrologers/gifts", icon: Gift },
      { title: "Skills", url: "/astrologers/skills", icon: BookOpen },
      { title: "Categories", url: "/astrologers/categories", icon: Layers },
      {
        title: "Commission Rate for Calls/Chats",
        url: "/astrologers/commission-rate",
        icon: DollarSign,
      },
    ],
  },
  {
    title: "Blogs",
    url: "/blogs",
    icon: FileText,
  },
  {
    title: "News",
    url: "/news",
    icon: Newspaper,
  },
  {
    title: "Banner Management",
    url: "/banner-management",
    icon: Image,
  },
  {
    title: "Stories",
    url: "/stories",
    icon: PlayCircle,
  },
  {
    title: "Custom Notifications",
    url: "/custom-notifications",
    icon: Bell,
  },
  {
    title: "Earning",
    url: "#",
    icon: Wallet,
    children: [
      { title: "Withdrawal Requests", url: "/earning/withdrawal-requests", icon: CreditCard },
      { title: "Withdrawal Methods", url: "/earning/withdrawal-methods", icon: Coins },
      { title: "Wallet History", url: "/earning/wallet-history", icon: Wallet },
    ],
  },
  {
    title: "General Settings",
    url: "/general-settings",
    icon: Settings,
  },
  {
    title: "Session",
    url: "/session",
    icon: CalendarClock,
  },
  {
    title: "Feedback",
    url: "/feedback",
    icon: Smile,
  },
  {
    title: "Team Management",
    url: "#",
    icon: Users2,
    children: [
      { title: "Team Role", url: "/team-management/team-role", icon: UserCheck },
      { title: "Team List", url: "/team-management/team-list", icon: Users },
    ],
  },
  {
    title: "Page Management",
    url: "/page-management",
    icon: Layers,
  },
  {
    title: "Contact Form",
    url: "/contact-form",
    icon: UserPlus,
  },
];
